### ISSUE TITLE
support tfenv as optional for homebrew

### ISSUE THREAD

**Issue by jlund69** [im2nguyen/rover#100]
I think it should be easy enough to support both **tfenv** and **terraform** for homebrew.
The current **_terraform_** requirement could be changed to recommended, and **_tfenv_** can be added as optional.  Then terraform-rover could be installed via brew with either.  (or neither)

It would look like this in the brew formula:
> depends on "terraform" => :recommended
> depends on "tfenv" => :optional

Q: Is there anything else that should be done?
Perhaps having the brew formula ensure that tfenv has a minimum version of terraform installed?

regards,
John

@SMillerDev @im2nguyen @yu-iskw

**Comment by SMillerDev** [comment]
Optional is not allowed in homebrew core but you can do this in a personal tap.

**Comment by jlund69** [comment]
How about just setting terraform as recommended?  Those that use tfenv, could use the --skip-recommended flag when installing.
In the package description note that users who have terraform available via method other than the brew terraform package can install rover via brew with --skip-recommended, but will need to validate their terraform install/configuration works with rover on their own.

@SMillerDev

**Comment by jlund69** [comment]
for now I'm using **ignore-dependencies** and installing via bundle.  Knowing the deps are actually installed via the bundle.
It is working.  As using **ignore-dependencies** does work I'll close this ticket.  Thanks for the quick responses.
