### ISSUE TITLE
SIGSEGV in map.go line 250

### ISSUE THREAD

**Issue by palmobar** [im2nguyen/rover#106]
Hi, sometimes `configs[parentConfig].Module.ModuleCalls[matchBrackets.ReplaceAllString(re.Name, "")]` can be `nil` which leads to SIGSEGV, I've patched it in a following way:

```
if configured && !childIndex.MatchString(id) && configs[parentConfig].Module.ModuleCalls[matchBrackets.ReplaceAllString(re.Name, "")] != nil {
```

**Comment by im2nguyen** [comment]
Hi, can you create a PR for this?

**Comment by palmobar** [comment]
Should have done that from the start ;>
https://github.com/im2nguyen/rover/pull/108
