### ISSUE TITLE
Azure isn't supported?

### ISSUE THREAD

**Issue by assapir** [im2nguyen/rover#15]
Trying to run `Rover` tool on Azure-based terraform, but it fails with

```
2021/08/31 12:48:38 Initializing Terraform...
2021/08/31 12:48:45 Unable to parse Plan: exit status 1

Error: Error building ARM Config: Please ensure you have installed Azure CLI version 2.0.79 or newer. Error parsing json result from the Azure CLI: Error launching Azure CLI: exec: "az": executable file not found in $PATH.
```

**Comment by im2nguyen** [comment]
Hello @assapir! Are you able to run `terraform plan` locally?

Rover is trying to generate a plan, but it's not able to. Can you check if you [configured the Azure provider correctly](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#authenticating-to-azure)?

**Comment by assapir** [comment]
Yes, it's working because I have azure-cli installed locally, but it's not installed in the docker image.

**Comment by assapir** [comment]
Sorry for not writing that I was running it from inside the docker image

**Comment by assapir** [comment]
If you want, @im2nguyen I can try to create a PR for adding azure-cli into the docker image

**Comment by im2nguyen** [comment]
I'm going to close out this issue. Instructions for setting up Azure credentials in Docker container can be found in https://github.com/im2nguyen/rover/pull/16. Thanks for reporting though @assapir !
