### ISSUE TITLE
[Feature Request] rover support to terraform workspaces 

### ISSUE THREAD

**Issue by vinayatnie** [im2nguyen/rover#18]
First this tool is awesome!!
we use terraform workspaces heavily and would love to have a way to pass the terraform workspace select command some how. Let me know if there is a way! 

thanks!

**Comment by vinayatnie** [comment]
this is for local rover on mac (not running as docker container)

**Comment by im2nguyen** [comment]
This isn't implemented yet, but I'm curious to learn more about your use case (so I can implement it properly).

Would you like to see all the workspaces in one visualization or would you like to view one workspace at a time? For example:

```
$ rover -workspace workspaceName
```

**Comment by mcgillij** [comment]
one workspace at a time def would fit our use-case, not sure about OP's.

**Comment by im2nguyen** [comment]
This should be fixed with #32! Can you pull the latest Docker image and test it again? You can also re-download the binary 😄 

The new `workspaceName` flag allows you to select an existing Terraform CLI workspace.

```
$ rover  -workspaceName "development"
```

This flag assumes that the workspace already exists. If it doesn't, rover will throw an error.

```
$ rover   -workspaceName "production"
2021/09/28 02:33:46 Starting Rover...
2021/09/28 02:33:46 Initializing Terraform...
2021/09/28 02:33:46 Running in production workspace...
2021/09/28 02:33:46 Unable to parse Plan: Unable to select workspace (production): workspace "production" does not exist
exit status 1
```

**Comment by mcgillij** [comment]
Nice, I'll giver a spin and report back.

**Comment by mcgillij** [comment]
Just ran a quick test, got some weirdness, going to try with just the binary outside the container later today when I have a chance.
```
2021/09/28 14:47:55 Starting Rover...
2021/09/28 14:47:55 Initializing Terraform...
2021/09/28 14:48:08 Running in us-east-2-neil workspace...
2021/09/28 14:48:09 Generating plan...
2021/09/28 14:48:33 Parsing configuration...
2021/09/28 14:48:33 Generating resource overview...
panic: interface conversion: interface {} is nil, not bool

goroutine 1 [running]:
main.(*rover).GenerateResourceOverview(0xc00015c2a0)
	/Users/dos/go/src/github.com/im2nguyen/rover/rso.go:87 +0x1d91
main.(*rover).generateAssets(0xc00015c2a0)
	/Users/dos/go/src/github.com/im2nguyen/rover/main.go:168 +0x167
main.main()
	/Users/dos/go/src/github.com/im2nguyen/rover/main.go:114 +0x959
```

**Comment by mcgillij** [comment]
This could be due to using 0.14.3 version of `terraform` in the docker image and not 1.0.7 (that you had in there).

**Comment by im2nguyen** [comment]
I'm going to close this issue for now, if people are experiencing similar issues, please let me know
