### ISSUE TITLE
Rover & CDK for Terraform & Azure CLI

### ISSUE THREAD

**Issue by andreasasujacgi** [im2nguyen/rover#19]
Hi,

First of all Rover seems great!

But, I'm trying to use Rover on a CDK for Terraform -project (CDKTF). It is understandable, that Rover does not work in the basedir of the CDK project. So, I `cd` to the dir where CDKTF creates the Terraform JSON. In that dir what happens is:
```
% ls
cdk.tf.json     plan
% docker run --rm -it -p 9000:9000 -v $(pwd):/src im2nguyen/rover
2021/09/24 07:50:10 Starting Rover...
2021/09/24 07:50:10 Initializing Terraform...
2021/09/24 07:50:10 Unable to parse Plan: exit status 1

Error: Error building ARM Config: Please ensure you have installed Azure CLI version 2.0.79 or newer. Error parsing json result from the Azure CLI: Error launching Azure CLI: exec: "az": executable file not found in $PATH.


% az --version                                                   
azure-cli                         2.28.0

core                              2.28.0
telemetry                          1.0.6

Python location '/usr/local/Cellar/azure-cli/2.28.0/libexec/bin/python'
Extensions directory '/Users/andreas.asuja/.azure/cliextensions'

Python (Darwin) 3.9.7 (default, Sep  3 2021, 12:37:55) 
[Clang 12.0.5 (clang-1205.0.22.9)]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```

I'm sorry I don't have time to dig more into this, but just to inform you.

**Comment by im2nguyen** [comment]
Hi @andreasasujacgi, glad you like it so far! The reason why it's not working is because the Docker image doesn't have the `az` CLI. I recommend using environment variables containing your Azure credentials to resolve this issue.

This [issue](https://github.com/im2nguyen/rover/issues/15)/[PR](https://github.com/im2nguyen/rover/pull/16) raised similar concerns. Please let me know if that helps!

--- 


First, create your service principal.

```
$ az ad sp create-for-rbac --role="Contributor" 
{
  "appId": "00000000-0000-0000-0000-000000000000",
  "displayName": "azure-cli-2017-06-05-10-41-15",
  "name": "http://azure-cli-2017-06-05-10-41-15",
  "password": "0000-0000-0000-0000-000000000000",
  "tenant": "00000000-0000-0000-0000-000000000000"
}
```

Then, [configure Terraform to use the service principal](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret#configuring-the-service-principal-in-terraform) by setting the following environment variables only (no CLI).

```
$ export ARM_CLIENT_ID="00000000-0000-0000-0000-000000000000"
$ export ARM_CLIENT_SECRET="00000000-0000-0000-0000-000000000000"
$ export ARM_SUBSCRIPTION_ID="00000000-0000-0000-0000-000000000000"
$ export ARM_TENANT_ID="00000000-0000-0000-0000-000000000000"
```

The provider block will automatically use these to auth to Azure.

```
# Configure the Microsoft Azure Provider
provider "azurerm" {
  features {}
}
```

**Comment by andreasasujacgi** [comment]
But ofcourse... Thanks, I'll give it a try.

**Comment by im2nguyen** [comment]
Going to close this, if you're still experiencing this issue, can you comment/re-open on this issue? Thank you!

**Comment by therodfather** [comment]
Hey, any updates on this? I set the service principal but it still gave the same output.

**Comment by im2nguyen** [comment]
Hey @therodfather, did you pass the environment variables into the docker container? 

The Azure provider defaults to using the `az` CLI when it doesn't detect the necessary environment variables to authenticate to Azure.

**Comment by therodfather** [comment]
I set the environment variables as show in the example above. I'm wondering if I got some of the information incorrect. Is there any other step besides exporting them?

**Comment by im2nguyen** [comment]
You could try downloading the rover binary and run it locally.

---

Just to confirm, these are the steps to export the Azure environment variables to the container.

```
$ printenv | grep "ARM" > .env
```

Then, add it as environment variables to your Docker container with `--env-file` flag.

```
$ docker run --rm -it -p 9000:9000 -v $(pwd):/src --env-file ./.env im2nguyen/rover
```

**Comment by therodfather** [comment]
> 
> 
> You could try downloading the rover binary and run it locally.
> 
> Just to confirm, these are the steps to export the Azure environment variables to the container.
> 
> ```
> $ printenv | grep "ARM" > .env
> ```
> 
> Then, add it as environment variables to your Docker container with `--env-file` flag.
> 
> ```
> $ docker run --rm -it -p 9000:9000 -v $(pwd):/src --env-file ./.env im2nguyen/rover
> ```

Yesssss! That was the missing info. Thank you!!
