### ISSUE TITLE
[Feature Request] How can rover use an already generated plan ?

### ISSUE THREAD

**Issue by soubinan** [im2nguyen/rover#20]
Thank you for this great tool!
It is really useful for a 4-eye plan checking.
But it will be really cool to be able to use rover directly with an already existing plan file (json or not) since some organization (as mine) are using some automation and abstraction stuff to generate plans and then apply them.
So as a for eye checking it will be very interesting.

Cheers :)

**Comment by Shocktrooper** [comment]
I second this we generate plan files in a separate CICD job then pass the output to linters and other jobs for checking. It would be nice if we can do the same with rover

**Comment by im2nguyen** [comment]
Will work on this next!

**Comment by jimmytoan** [comment]
Agree on this feature, it will allow people to run terraform commands by their ways to generate the plan file. For example, this is my way to support different backend/variables for each environment
`terraform init -backend-config=backend-envs/dev.tf`
`terraform plan -var-file=variables-envs/dev.tf`

And `rover` failed to init remote backend properly

**Comment by jurgen-weber-deltatre** [comment]
yeah, means you can integrate with runatlantis.io also. Let it init and plan, then I want to run rover into a dir. 

Run an nginx side car to serve the atlantis webserver and anything rover creates with the zip option and extract.

**Comment by sujithq** [comment]
> Will work on this next!

Take a look at this PR https://github.com/im2nguyen/rover/pull/27
I also modified the Dockerfile to use a multi stage approach.

**Comment by im2nguyen** [comment]
Hey all, the latest version should have this. If it works, can you 👍   this comment? Once there's enough 👍 s, I'll close this issue.

Please let me know if you have any feedback, thanks!

You can test this workflow by:

1. Go to `example/random-test` and run the following to generate a plan output.

    ```
    terraform plan -out plan.out
    ```

2.  Then, in the same directory, run the following command to force rover to use the plan file you specified

    ```
    docker run --rm -it -p 9000:9000 -v $(pwd):/src im2nguyen/rover -planPath plan.out
    ```

    To force `rover` to generate a visualization using the plan file only (no parsing the configuration), run the following command:

    ```
    docker run --rm -it -p 9000:9000 -v $(pwd):/src im2nguyen/rover -planPath plan.out -tfConfigExists=false
    ```

    You should see something like the following. Notice that there are no more file names in the visualization

    ![image](https://user-images.githubusercontent.com/7556325/135082937-94b61a78-0717-445f-b0e3-7b0b3ccf6cac.png)

**Comment by anthosz** [comment]
I just re-download the binary but I cannot use the plan :/ (free memory was available so I don't really understand the issue but the plan is bigger)

`
2021/09/28 17:13:30 Starting Rover...
2021/09/28 17:13:30 Using provided plan...
2021/09/28 17:13:39 Generating resource overview...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x757ce6]

goroutine 1 [running]:
main.(*rover).GenerateResourceOverview(0xc0001082a0)
        rover/rso.go:61 +0x226
main.(*rover).generateAssets(0xc0001082a0)
        rover/main.go:168 +0x167
main.main()
        rover/main.go:114 +0x959
`

**Comment by im2nguyen** [comment]
Oh that's interesting, this has to deal with rover trying to reference an attribute that doesn't exist. Is that the full error message? Can you c/p your full command you used?

**Comment by anthosz** [comment]
After a new tentative, it seems ok (I regenerated the plan from scratch) but unable to see something without freeze of browser (+1000 resources in the plan so probably related :))

Tried also with standalone mode, at the end, I have a plan.js of +10MB + rso.js +5MB

**Comment by im2nguyen** [comment]
Oh geez, 1000+ resources in one state seems intense. How do you keep track of everything?

How long do typical plans/applies take? (just curious)

**Comment by anthosz** [comment]
All is tracked via a repository (and managed via modules to have a clear view)
- The plan take several minutes
- Apply is depending of the plan/diff -> if only one thing change, take only few seconds :)

When I saw your project, I immediately knew that this is what we need... but well, plan is a little big :D

**Comment by anthosz** [comment]
To back to this issue, you can close it (I tested with a little plan and it works)

**Comment by soubinan** [comment]
It works fine for me also
Thank you @im2nguyen !

**Comment by jurgen-weber-deltatre** [comment]
amazing, tyvm!

**Comment by im2nguyen** [comment]
Hi @shanoor, we deprecated the `tfConfigExists` flag. Can you try running `rover_v -planPath test.tfplan`?
