### ISSUE TITLE
Panic on deleting resource from tf file

### ISSUE THREAD

**Issue by evleria** [im2nguyen/rover#26]
Rover fails with panic if I delete a resource from .tf file:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7e222f]

goroutine 1 [running]:
main.GenerateResourceOverview(0xc000076de0, 0x1)
        /home/lera/go/src/github.com/im2nguyen/rover/rso.go:125 +0xf2f
main.generateAssets(0x89c21b, 0x5, 0x7fff859df85e, 0x32, 0x7fff859df83f, 0x12, 0xc0000eca70, 0x1, 0x1, 0xc0000eca80, ...)
        /home/lera/go/src/github.com/im2nguyen/rover/main.go:114 +0x2b9
main.main()
        /home/lera/go/src/github.com/im2nguyen/rover/main.go:61 +0x625
```

The problem is the absence of an entry for deleted resource in `map[string]*ResourceOverview`. It's created for each resource in a plan, but if it was deleted then it appears only in changes.
Anyway, creating this entry before saving a corresponding change just saves from an error. Rover won't create a node for it in the resulting overview.

**Comment by im2nguyen** [comment]
Thanks for reporting! I'll look into this right away

**Comment by im2nguyen** [comment]
Hey @evleria, can you list the steps to reproduce this? Not completely sure how to reproduce this scenario

It also seems like an important and common workflow where it'll be nice to add it to the next release ([v0.2.0](https://github.com/im2nguyen/rover/pull/32))

**Comment by evleria** [comment]
Hi, @im2nguyen. Thank you for responding.

**Steps to reproduce:**
1. Create `.tf` file with some resources
2. Run `terraform apply` and create these resources
3. Remove any created resource from `.tf` file
4. Run Rover

`terraform plan` should print delete action against the resource, but since it's no longer a part of `.tf` resource definition this problem occurs.

I hope I didn't miss anything.
