### ISSUE TITLE
[Feature Request] Hide data marked sensitive (variables)

### ISSUE THREAD

**Issue by sams83** [im2nguyen/rover#29]
Hi,

I  discover this great tool last week.

It is possible to hide or crypte somes sensitives data like password in Terraform Visualiser  ?

The password is displayed  when we get the details of VAR

Thank you!

sams83

**Comment by im2nguyen** [comment]
This should be fixed with #32! Can you pull the latest Docker image and test it again? You can also re-download the binary 😄 

```
docker pull im2nguyen/rover
```
