### ISSUE TITLE
terraform modules in relative subdirectories

### ISSUE THREAD

**Issue by zimmdi** [im2nguyen/rover#30]
Hi,
we do have the terraform modules relative to the environment related files. Is it possible to use rover with this setup?
/env/env_name/main.tf
/env/env_name/state.conf ... configuration.auto.tfvars.... etc
/terraform_modules/mod1
/terraform_modules/mod2

Where e.g. main.tf points to module ../../terraform_modules/module1

Thanks

**Comment by im2nguyen** [comment]
It _should_ work. Based on your description, this is similar to the [`random_test` example](https://github.com/im2nguyen/rover/tree/main/example/random-test) 

Rover parses all the configuration in the current directory and its subdirectories. Since your module config is hosted outside of where your config is located, it might throw an error while graphing the resources.

Once https://github.com/im2nguyen/rover/issues/20 is resolved (hoping by end of week), you should be able to use Rover for your configuration

**Comment by zimmdi** [comment]
Hi,
thanks for the quick response.
In the example the modules are relative within subdirectories of the base configuration. In our case these are "outside" of it. I did understand that the base "starter" configuration is in /src folder. In my case the it cant address the modules because you cant go two directories up.  For my case there is the need of a "starting folder" if you like. I will check if the #20 would solve it and get back if needed

**Comment by im2nguyen** [comment]
https://github.com/im2nguyen/rover/pull/32 will "address" this. For this scenario, you will need to generate a plan then run rover against the plan file 😄 

```
$ rover -planPath "plan.out"
```

**Comment by im2nguyen** [comment]
Just merged #32, so this _should_ work.

If it works, can you 👍   this comment? Once there's enough 👍 s, I'll close this issue.

Please let me know if you have any feedback, thanks!

You can test this workflow by:

1. Go to `example/random-test` and run the following to generate a plan output.

    ```
    terraform plan -out plan.out
    ```

2.  Then, in the same directory, run the following command to force rover to use the plan file you specified

    ```
    docker run --rm -it -p 9000:9000 -v $(pwd):/src im2nguyen/rover -planPath plan.out
    ```

    To force `rover` to generate a visualization using the plan file only (no parsing the configuration), run the following command:

    ```
    docker run --rm -it -p 9000:9000 -v $(pwd):/src im2nguyen/rover -planPath plan.out -tfConfigExists=false
    ```

    You should see something like the following. Notice that there are no more file names in the visualization

    ![image](https://user-images.githubusercontent.com/7556325/135082937-94b61a78-0717-445f-b0e3-7b0b3ccf6cac.png)

**Comment by rvanider** [comment]
v0.2.1 gives me the following:

```
vue-cytoscape.common.js:2465 Uncaught (in promise) Error: Can not create edge `module.cloud-config->module.network` with nonexistant source `module.cloud-config`
    at Pe (vue-cytoscape.common.js:2465)
    at Xe.so.restore (vue-cytoscape.common.js:14039)
    at new Xe (vue-cytoscape.common.js:2877)
    at Ko.add (vue-cytoscape.common.js:14474)
    at Graph.vue:354
    at Array.forEach (<anonymous>)
    at o.renderGraph (Graph.vue:333)
    at Graph.vue:519
```

Executed as follows: `./rover_v0.2.1 --planPath plan.bin --tfConfigExists=false`

**Comment by im2nguyen** [comment]
Oh interesting, which module is external?

**Comment by rvanider** [comment]
Both are local sub-folders.

**Comment by zimmdi** [comment]
Hi,
cannot test it here directly with your image (as the plan is 0.14.5) 
Building a Docker file on my own (the current in your branch is not working) with version 0.14.5 shows modules and data. Not all data (plan has Plan: 3 to add, 4 to change, 9 to destroy.)
nothing of this is shown (maybe because of the TF version i use.
And the rover still needs AWS permissions for using the plan only.
I hope to be able to migrate TF to the latest and check again tomorrow.

**Comment by im2nguyen** [comment]
Thanks @rvanider, I'll test some more 😄
