### ISSUE TITLE
Possibility to reference tfvars file path

### ISSUE THREAD

**Issue by kgorskowski** [im2nguyen/rover#4]
Hi! 
Thanks for your effort. I was trying to play around with it but stumbled upon this "problem". Our setup divides stage dependent variables into tfvars in subfolders that are referenced in our CI environment.
Maybe its possible to imitate the `-var-file="testing.tfvars"` syntax from terraform here?

**Comment by im2nguyen** [comment]
Thanks for your feature request! The latest version should have the `tfVarsFile` and `tfVar` for you to define Terraform variables

You can download directly from the [release](https://github.com/im2nguyen/rover/releases/tag/v0.1.5) or pull the latest Docker image.

```
$ docker pull im2nguyen/rover:latest
```
