### ISSUE TITLE
Rover looks for Terraform in specific location

### ISSUE THREAD

**Issue by KoenR3** [im2nguyen/rover#45]
Startup logs:
```
2021/10/04 09:17:50 Unable to parse Plan: fork/exec /usr/local/bin/terraform: no such file or directory
```

Now my Terraform is located in another location as it is set up to easily upgrade per user.  Is there a way to override this?

**Comment by sujithq** [comment]
@KoenR3 use the tfPath parameter to provide a different terraform path

**Comment by grafanalf** [comment]
@KoenR3 yeah, supply `-tfPath /usr/bin/terraform` for example, to tell Rover to use Terraform binary from another location.

**Comment by KoenR3** [comment]
Thanks, should have checked `--help``

**Comment by ADTC** [comment]
But why is this necessary? Couldn't `rover` just run `terraform` wherever it may be? Or at least check the output from `which terraform` automatically and use that.
