### ISSUE TITLE
[Feature Request] A way to create the PNG only.

### ISSUE THREAD

**Issue by jontreharne** [im2nguyen/rover#46]
Hi,

Our usecase is to update the documentation with a static image only.
So ideally the rover would create the png and we can archive it in our gitlab CI pipeline.

Ive tried with the static assets zip file but it does no appear to be included.

Interactive console is not required.

**Comment by jontreharne** [comment]
Hi - Any idea if this is targeted for a release?
Thank you

**Comment by im2nguyen** [comment]
Not sure, rover's UI generates the image, so the only thing I can think of to implement this is to generate a headless browser that opens the page then save the static image only. As a result, I'm thinking this would only be supported in a Docker image, that way I can better control the environment (ensure headless chrome is installed) without making the rover binary large.

Haven't experimented with this yet... but open to PRs
