### ISSUE TITLE
Use predefined TF plan for visualization

### ISSUE THREAD

**Issue by avarghese-sqsp** [im2nguyen/rover#51]
Hi. Thanks for developing this tool. I am not able to run the tool as it tries to generate the TF plan but my configuration uses symlinked files and environment variables to generate the plan. Could you support loading the details directly from a specified plan file instead of generating it on the fly?

**Comment by im2nguyen** [comment]
Hi @avarghese-sqsp, thanks for testing rover out! We already support this feature 😄 (Issue https://github.com/im2nguyen/rover/issues/9)


You can test this workflow by:

1. Go to `example/random-test` and run the following to generate a plan output.

    ```
    terraform plan -out plan.out
    ```

2.  Then, in the same directory, run the following command to force rover to use the plan file you specified

    ```
    docker run --rm -it -p 9000:9000 -v $(pwd):/src im2nguyen/rover -planPath plan.out
    ```

    To force `rover` to generate a visualization using the plan file only (no parsing the configuration), run the following command:

    ```
    docker run --rm -it -p 9000:9000 -v $(pwd):/src im2nguyen/rover -planPath plan.out -tfConfigExists=false
    ```

    You should see something like the following. Notice that there are no more file names in the visualization

    ![image](https://user-images.githubusercontent.com/7556325/135082937-94b61a78-0717-445f-b0e3-7b0b3ccf6cac.png)

**Comment by avarghese-sqsp** [comment]
I tried to run with the above approach and I got a complaint about symlinked files not being available. I also use a bunch of configurations via environment variables & use TF workspace, which altogether doesn't seem to be a good use-case for this app.

I definitely love what you have tried to do here. Thank you very much for building this application!

**Comment by d-henn** [comment]
Does this work for plans retrieved from the Terraform Cloud API? I see there is a request to integrate with TFC, but just wondering if there is a way to leverage the API in the meantime?

**Comment by im2nguyen** [comment]
Yep! You can request the TFC API to [retrieve the execution plan](https://www.terraform.io/docs/cloud/api/plans.html#retrieve-the-json-execution-plan), then pass that file as an input into rover

**Comment by d-henn** [comment]
I did unfortunately it looks like under the hood it uses `terraform show`. At least when I tried it wouldn't allow a json file, it had to be an actual `plan` output :(.

Received error:

```
Terraform couldn't read the given file as a state or plan file.
The errors while attempting to read the file as each format are
shown below.

State read error: Error reading json-output.json as a statefile: Unsupported state file format: The state file does not have a "version" attribute, which is required to identify the format version.

Plan read error: zip: not a valid zip file
```

**Comment by im2nguyen** [comment]
Oh interesting, I'll look into supporting this. Thanks for raising this issue!

**Comment by d-henn** [comment]
Awesome thanks @im2nguyen! Do you need me to create a separate issue for this particular case?

**Comment by im2nguyen** [comment]
I would rather use https://github.com/im2nguyen/rover/issues/34 to track this instead. Since we can use a predefined TF plan for visualization, I'm going to close this issue 😄

**Comment by im2nguyen** [comment]
@d-henn, I posted an update to #34 that you can build locally and use for the time being 😄
