### ISSUE TITLE
Rover visualization is not displaying in proper format

### ISSUE THREAD

**Issue by gauravjain77** [im2nguyen/rover#58]
![rover](https://user-images.githubusercontent.com/89442747/138717571-b70f781d-d1bd-4bc7-8c31-b4f70e13b7a3.png)

**Comment by jonwilliams84** [comment]
I am able to replicate this also:

![image](https://user-images.githubusercontent.com/24478629/144407858-3d8fbd07-9599-4c25-ab77-9c056dab1a66.png)

**Comment by im2nguyen** [comment]
Can you provide more information on how to replicate this? In addition, can you open up the console? There should be an error message when the graph fails to render like this

it'll help me in debugging the issue, thanks!

**Comment by jonwilliams84** [comment]
I am running 0.2.1 on Fedora Linux. (I downloaded the 0.2.2) binary but -version says 0.2.1.

All of my terraform is split out of main.tf into specific resource / service tf files, and I use env.tfvars to keep my code dry.  Almost every object managed by terraform is derived from an upstream module as opposed to individual resources. 

What other info would help?

**Comment by im2nguyen** [comment]
Hi @jonwilliams84, thanks! Can you open the visualization in your favorite browser, go to devtools and c/p the error message?

Also, what version of Terraform are you running?

**Comment by dsab123** [comment]
Hello, really enjoying this package, @im2nguyen ! 

I'm running into the same visualization issue. 

![image](https://user-images.githubusercontent.com/3699629/145633781-90d9fa3d-c911-4487-b427-0610e16d4b42.png)


The error is:

```vue-cytoscape.common.js:2465 Uncaught (in promise) Error: Can not create edge `azurerm_cosmosdb_account.combine-db->azurerm_resource_group.Sequoia-Combine-RG.name` with nonexistant target `azurerm_resource_group.Sequoia-Combine-RG.name`
    at Te (vue-cytoscape.common.js:2465)
    at Ke.so.restore (vue-cytoscape.common.js:14039)
    at new Ke (vue-cytoscape.common.js:2877)
    at Xo.add (vue-cytoscape.common.js:14474)
    at Graph.vue:336
    at Array.forEach (<anonymous>)
    at o.renderGraph (Graph.vue:332)
    at Graph.vue:494

**Comment by im2nguyen** [comment]
Thank you! I'll look into this soon 😄
