### ISSUE TITLE
Generate standalone html

### ISSUE THREAD

**Issue by techdragon** [im2nguyen/rover#6]
It would be very useful to be able to generate the visualisation in a format that can be generated as part of a build pipeline triggered by a pull request or other terraform automated workflows. These situations cant leave servers up and running in order to browse to the visualisation, so in a nutshell we need standalone "archiving" versions of the visualisations in these situations. 

It can be as simple as generating a zipped up folder full of HTML/CSS/JS,  but having some kind of standalone _archivable_ output would be fantastic.

**Comment by im2nguyen** [comment]
Thanks for your feature request! The latest version should have the standalone mode.

You can download directly from the [release](https://github.com/im2nguyen/rover/releases/tag/v0.1.6) or pull the latest Docker image.

```
$ docker pull im2nguyen/rover:latest
```

--- 

Standalone mode generates a `rover.zip` file containing all the static assets.

```
$ docker run --rm -it -v $(pwd):/src im2nguyen/rover -standalone true
```

After all the assets are generated, unzip `rover.zip` and open `rover/index.html` in your favorite web browser.
