### ISSUE TITLE
Issue: Save Graph not working

### ISSUE THREAD

**Issue by mpender** [im2nguyen/rover#60]
First off, this is a great tool! 

Im trying to save the output to present in documentation etc etc 
When the image is downloaded, it says its always empty.
Tried different browsers etc and no change. 

Can workaround using straight screenshots of the display. 

Bonus : Could we get a full screen mode of the actual visualization ? i.e remove the legend and what not so we can move around large TF code 

Platform : OSX
Version : rover_0.2.2_darwin_amd64

**Comment by im2nguyen** [comment]
I can't seem to reproduce this problem... can you try to reproduce it and look at any messages in the console?

**Comment by mpender** [comment]
Hi There, yes sure. Il try to recreate and get some diagnostic info
