### ISSUE TITLE
Terraform Visualizer - Resources in the graph are on top of each other

### ISSUE THREAD

**Issue by KarthikRajashekaran** [im2nguyen/rover#70]
Hi,

When I go to the Rover - Terraform Visualizer, all the resources are on top of each other in the center of the graph.

Am I missing anything 
![image](https://user-images.githubusercontent.com/33160284/146810084-42161820-d0e7-41be-9264-69d5124ad6d3.png)

Thank you!
Karthik

**Comment by DadouneDa** [comment]
Hi @KarthikRajashekaran , it happened to me as well, I downloaded the new version (win binary) v0.3.0 and it's working, try it out
