### ISSUE TITLE
Graph items are overlapping each other 

### ISSUE THREAD

**Issue by DadouneDa** [im2nguyen/rover#75]
Hi, 
As said before me, it's a cool project, I hope it will work for me as well (:

My Env:

- rover_0.1.3_windows_amd64
- Terraform v1.0.10
- azurerm v2.84.0

My CLI:
```
terraform init
terraform plan -out tfplan
rover -tfPath "C:\Program Files\terraform\terraform.exe"
```

I applied the Rover my full infra project including ~26 resources and the graph items were overlapping each other like a stack.

I then tried to use a simpler infra with only 3 resources, and it also had all the items one above the other

Is there an issue there or am I doing something wrong?

![image](https://user-images.githubusercontent.com/82889007/147543129-1908446f-1f74-4752-8551-ac2a9658b9f0.png)

**Comment by im2nguyen** [comment]
Hey @DadouneDa, can you try again? If it's occurring, can you open up your browser console c/p the error message? thank you!

**Comment by DadouneDa** [comment]
Hi @im2nguyen, I ran it again and it reoccurs, the output in the console is:

![image](https://user-images.githubusercontent.com/82889007/149078091-c561276a-f5ec-4668-8e88-ff35ba56da9f.png)

**Comment by im2nguyen** [comment]
Interesting... are you able to run the `example/random-test` one successfully?

can you send sample config that can reproduce the error?

**Comment by DadouneDa** [comment]
The `example\random-test` is not working as well 
![image](https://user-images.githubusercontent.com/82889007/149125698-35af2190-f8d2-4b43-9c3f-7c3100160db8.png)

**Comment by im2nguyen** [comment]
That's... really interesting. Which browser are you using? How are you running the command from your terminal? Are you using docker or did you download the binary locally?

**Comment by DadouneDa** [comment]
I tried with both Chrome and Edge and Firefox.
I'm running this command via the CMD terminal `rover -tfPath "C:\Program Files\terraform\terraform.exe"`
I'm using the win binary exe

I also tried with another PC and I got the same issue
