### ISSUE TITLE
Unsupported State Format Version >= "1.0"

### ISSUE THREAD

**Issue by dontmint** [im2nguyen/rover#78]
**Problem**

Rover can not parse Terraform plan version >= "1.0"

```
./rover_v0.2.2
Starting Rover...
Initializing Terraform...
Generating plan...
Unable to parse Plan: Unable to read Plan: unsupported state format version: expected ["0.1" "0.2"], got "1.0"
```

**Version**
Terraform: v1.1.2
Rover: 0.2.2
Platform: darwin_arm64 (Apple M1)

I init my new infrastructure using TF version v1.1.2, please add support for the latest version. 
Thanks in advance.

**Comment by im2nguyen** [comment]
This latest PR should resolve your issue. Gonna take some time for the Docker image to complete building but please let me know if it resolves your issue 😄
