### ISSUE TITLE
Unsupported state format version: expected ["0.1" "0.2"], got "1.0"

### ISSUE THREAD

**Issue by IvanovOleg** [im2nguyen/rover#80]
Rover has issues with terrafrom 1.1.3
2022/01/12 20:54:28 Unable to parse Plan: Unable to read Plan: unsupported state format version: expected ["0.1" "0.2"], got "1.0"

**Comment by im2nguyen** [comment]
Hello! Are you using v0.3.0? The latest version supports Terraform 1.1+

**Comment by EugenMayer** [comment]
User TIF 1.1.2 and 1.1.3 without any of those issues here, so works for me :)

**Comment by IvanovOleg** [comment]
I tested with 0.2.2, since 0.3 was not available at that time. I will try 0.3

**Comment by IvanovOleg** [comment]
Works with 0.3
