### ISSUE TITLE
Feature-Request: Button to show changing resources only

### ISSUE THREAD

**Issue by EugenMayer** [im2nguyen/rover#81]
Due to the amount of modules and nested modules, the graph is huge in our case:

![image](https://user-images.githubusercontent.com/136934/149362971-ac27fbf1-cbda-45e1-8472-3076f3a70d22.png)

It would be really helpful to be able to limit the graph (using a button in the UI) to resources which are going to change. This helps getting an overview a lot better.

What do you think?

**Comment by im2nguyen** [comment]
This makes sense. Would this be related to this ticket (https://github.com/im2nguyen/rover/issues/82)? Have buttons where it'll allow you to filter out resources in the graph view?

**Comment by EugenMayer** [comment]
Somewhat I guess - I think it should be a checkbox instead of a button to emphasise it stays selected all the time, so one can combine 'changed only' with 'deleted only' - does this make sense to you?
