### ISSUE TITLE
Feature-Request: Filter using the resource-button

### ISSUE THREAD

**Issue by EugenMayer** [im2nguyen/rover#82]
It would be awesome to be able to click on `Resource-Delete` and only show those resources, which are deleted. Same for created/updated. It would make traversing and understanding the changes a lot easier, splitting the visuals into parts to inspect.

What is your take on that?

**Comment by im2nguyen** [comment]
That makes sense! If I'm understanding you correctly, this feature will help users filter based on resource action (created, updated, delete, etc)
