### ISSUE TITLE
Bug: No way to 'unclick a resource'

### ISSUE THREAD

**Issue by EugenMayer** [im2nguyen/rover#83]
When one selects a resources the the graph, there is no way to unselect it - the only way is to reload the page entirely.

This could be a side effect of nested modules.

**Comment by im2nguyen** [comment]
If you click on the root resource (the background), you should be able to unselect it.

I noticed selecting/unselecting resource is a little buggy tho, will look into it 😄

**Comment by EugenMayer** [comment]
It is not easy to get to the background at all for me :) The chart is huge right now, since it does show more then "changed" and thus it's hard. But i also tried it to click on the backround, since it is the natural way of doing that, it did not work for me. Maybe this is a other thing with nested modules, since the entire graph is nested in one nested module in the end and you cannot really click on a free background this way?

**Comment by ZeChArtiahSaher** [comment]
Also would be nice if there was some simple support for at least macbook touchpad for two finger panning. Currently UI behaves the same with panning/pitching.
