### ISSUE TITLE
[Feature Request] Provide json plan file instead of generating plan

### ISSUE THREAD

**Issue by fraserc182** [im2nguyen/rover#9]
Is it possible to supply a json formatted plan instead of running a terraform plan command?
I am asking because we use TF cloud and for us it would be easier to query the api to get this json plan.
https://www.terraform.io/docs/cloud/api/plans.html#retrieve-the-json-execution-plan

**Comment by im2nguyen** [comment]
This is a great idea!

I'm currently working on this, but it's taking a little bit more time since the graph and the resource explorer needs access to the configuration.

Will let you know when it's out

**Comment by fraserc182** [comment]
Brilliant, thanks for the update! Happy to do any testing as well if it would be helpful.

**Comment by tuxknight** [comment]
Brilliant, thanks for the update! Happy to do any testing as well if it would be helpful too.

**Comment by ypismerov** [comment]
But, to be fair, “terraform plan” works just fine locally with TFE, even in the (default) remote execution mode set in the workspace, as long as you have the workspace pointed to your TFE cloud one in the code.

**Comment by im2nguyen** [comment]
Hey all, the latest version should have this. If it works, can you 👍   this comment? Once there's enough 👍 s, I'll close this issue.

Please let me know if you have any feedback, thanks!

You can test this workflow by:

1. Go to `example/random-test` and run the following to generate a plan output.

    ```
    terraform plan -out plan.out
    ```

2.  Then, in the same directory, run the following command to force rover to use the plan file you specified

    ```
    docker run --rm -it -p 9000:9000 -v $(pwd):/src im2nguyen/rover -planPath plan.out
    ```

    To force `rover` to generate a visualization using the plan file only (no parsing the configuration), run the following command:

    ```
    docker run --rm -it -p 9000:9000 -v $(pwd):/src im2nguyen/rover -planPath plan.out -tfConfigExists=false
    ```

    You should see something like the following. Notice that there are no more file names in the visualization

    ![image](https://user-images.githubusercontent.com/7556325/135082937-94b61a78-0717-445f-b0e3-7b0b3ccf6cac.png)
