### ISSUE TITLE
Invalid visualization

### ISSUE THREAD

**Issue by nonbeing** [im2nguyen/rover#93]
As was being discussed in #90, according to @JackFlukinger, there's an issue in the visualization of my AWS-based TF state.

SVG generated by Rover is here: https://file.io/YJrw7hJXmSEp

Let's discuss and fix this issue here instead of in the original bug meant for the panic that got fixed.

> Okay @nonbeing , definitely not intended. Where is the `data.aws_iam_policy_document.webhook_sns_topic_policy` supposed to be housed? Should be a simple fix.

I'm not sure I understand, @JackFlukinger ... Could you please explain what the issue is?

**Comment by nonbeing** [comment]
When I run `terraform plan` this is one of the snippets of the output related to `data.aws_iam_policy_document.webhook_sns_topic_policy`:


```
  # module.admin.module.sparkpost_webhook.data.aws_iam_policy_document.webhook_sns_topic_policy will be read during apply
  # (config refers to values not yet known)
 <= data "aws_iam_policy_document" "webhook_sns_topic_policy"  {
      ~ id        = "2653013193" -> (known after apply)
      ~ json      = jsonencode(
            {
              - Id        = "events_publish_to_SNS"
              - Statement = [
                  - {
                      - Action    = "sns:Publish"
                      - Condition = {
                          - StringEquals = {
                              - AWS:PrincipalAccount = [
                                  - "361505717140",
                                ]
                            }
                        }
                      - Effect    = "Allow"
                      - Principal = {
                          - AWS = "*"
                        }
                      - Resource  = "arn:aws:sns:us-east-1:361505717140:dev-sparkpost-webhook-20210809013713574400000002"
                      - Sid       = "AllowAnythingWithinTheAccountToPublish"
                    },
                  - {
                      - Action    = "sns:Publish"
                      - Effect    = "Allow"
                      - Principal = {
                          - Service = "events.amazonaws.com"
                        }
                      - Resource  = "arn:aws:sns:us-east-1:361505717140:dev-sparkpost-webhook-20210809013713574400000002"
                      - Sid       = "AllowEventsToPublishToSNS"
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> (known after apply)
      - version   = "2012-10-17" -> null
        # (1 unchanged attribute hidden)

      ~ statement {
          - not_actions   = [] -> null
          - not_resources = [] -> null
            # (4 unchanged attributes hidden)


            # (2 unchanged blocks hidden)
        }
      ~ statement {
          - not_actions   = [] -> null
          - not_resources = [] -> null
            # (4 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }
    }
```

The above diff also occurs for another module, `module.pay_and_resolve.module.stripe_webhook.data.aws_iam_policy_document.webhook_sns_topic_policy`

As far as I can tell, this is just noise. My TF plan seems to contain a lot of noise; despite `apply`ing it, every plan contains 28 diffs that never go away and this is one of them.

Does this information help you?

**Comment by JackFlukinger** [comment]
Yes, that's very helpful!

So the issue is that `data.aws_iam_policy_document.webhook_sns_topic_policy` belongs in the `stripe_webhook` module, but in the visualization it's completely outside the purple backdrop. 

It should be a quick fix, but can you send an image of: the `details` block on the left side of rover after you click `data.aws_iam_policy_document.webhook_sns_topic_policy`? I may also send a binary a bit later that prints some debug messages.

**Comment by nonbeing** [comment]
@JackFlukinger I've hosted the Rover UI for my TF state over at http://rover.anatta.space - please feel free to use this link to check the full visualization as you need.

**Comment by JackFlukinger** [comment]
Thanks so much @nonbeing , I'll get to this in more depth tomorrow.

**Comment by nonbeing** [comment]
@JackFlukinger any chance you can take a look at this in the next week?

**Comment by JackFlukinger** [comment]
Hey @nonbeing , I'm planning to, got derailed by a concussion last week.

**Comment by nonbeing** [comment]
Ouch, take care. Take a look whenever you're better, no issues.

**Comment by JackFlukinger** [comment]
Hey @nonbeing , I'm getting back into it. Can you clone the linked PR, rebuild rover on your end, and re-host the visualization you have up right now? Make sure to rebuild the frontend with `npm run build` before you `go install`. This will just print some helpful debug messages for me :).

**Comment by JackFlukinger** [comment]
Whoops, sorry @nonbeing -- forgot you don't have a go dev setup. Here's the binary: https://file.io/p1uqibJBpeFh

**Comment by nonbeing** [comment]
Thank you for the binary, but I'm running Rover on an Ubuntu AMD64 VM on GCP, so it didn't work. 

Rather than troubling you again for a new binary, I finally got my Go dev setup done on my MacBook Pro. I cloned your PR (97) locally, then cross-compiled the rover binary for Ubuntu with `GOOS=linux GOARCH=amd64 go build`, then`scp`ed  it over to the GCP VM and restarted Rover.

I believe the new `console.log(this.graph)` is now visible:

<img width="801" alt="image" src="https://user-images.githubusercontent.com/897313/156692688-cca195f6-5f32-48d8-855c-d3c24d2c16df.png">


Please check http://rover.anatta.space at your convenience.

**Comment by JackFlukinger** [comment]
Sweet, I'll check this out tomorrow!

**Comment by JackFlukinger** [comment]
I understand the problem now! Kind of a tricky one, makes sense that it didn't get tested out. Writing this out so I remember tomorrow.

When two resources have the same resource type (e.g. `aws_ssm_parameter`) and they are in different files in the _same module_, rover only has one node for `aws_ssm_parameter`, because the resource "id" is the same (e.g. `module.network.aws_ssm_parameter`). 

So I just need to make the ids unique for the same resource type in different files :).

**Comment by JackFlukinger** [comment]
Okay @nonbeing , try the PR now, believe it's fixed :).

**Comment by nonbeing** [comment]
Thanks, will do!
