### ISSUE TITLE
0.3.1 checksum changed

### ISSUE THREAD

**Issue by iMichka** [im2nguyen/rover#96]
Hi. I am a maintainer of the Homebrew package manager.
We noticed that the checksum of the 0.3.1 release has changed from (sha256): 8d880bdd2a4f0c6817c71d5da4e22c5ba5dafa2cec712101950fce530f20ea12 to 72b86f11f0674e88c01753e262947425e8ff4396aacfe03ddb7d3bf17b89e8dd

This is a major security issue as upstream release checksums are not supposed to change. Did you retag the release (which is something that should never been done, see https://git-scm.com/docs/git-tag#_discussion). Or did someone gain access to your repo?

See https://github.com/Homebrew/homebrew-core/pull/95105 for the issue on our side.

**Comment by im2nguyen** [comment]
I accidentally retag the release. My bad, what can I do to resolve it?

**Comment by iMichka** [comment]
Thanks for the clarification. Right now it's too late for that release.

Next time the best is probably to leave the tag on the old commit, and create a new 0.3.2 release instead.
